permalink: /:month-:day-:year/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true

# Theme settings
theme:

  # Site name
  site_name: Cargo Cult Blog

  # Google analytics UID
  google_analytics_uid: UA-40479541-1

  # Disqus shortname, for comments
  # disqus_shortname: ???

  # Number of featured posts on homepage
  homepage_featured: 1

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 3

  # Number of words to display in post summaries
  featured_wordcount: 20

production_url : http://nautilusapps.github.io
